import type { Metadata } from 'next';
import './globals.css';

import { AppSidebar, Header, SidebarProvider } from '@/components';

export const metadata: Metadata = {
  title: 'Saas coding challenge',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Header />

        <div>
          <SidebarProvider>
            <AppSidebar />
            <main className="pt-14 w-full">{children}</main>
          </SidebarProvider>
        </div>
      </body>
    </html>
  );
}
